apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgA338qA3azSJdODu8j+eCNLThvQztFzA8KUEAK+AhOL/OW8WQ9Feqneyzh+1gxaSBqdwG0Zudo6zQzLyZOq1se+wHsn0oI0v77+J5vVXYXGtOezQem3q3gnMbwB08XMa8dN7mG8jZuaC1DqSze3N06s8/dMhMGNwk1pwfxRe3QT7Y53XiPSYu0F5OtFZ+e99v5tyr/wTHlzBuDDtF99OBTfdgR4+BqdfVksriK8WPWVMsSt4tjDPT8VRypw/8yA9HoQBPXcFCJ718VfAwarhGXhoT4vtK8W0pPwXgp1gPRtqUDRDxtDBrKu6MwceN63Xg68Wjw8PW2Y2KrHlMtQI43M49hLuNgjiOTCcLEb/2+Ggu2QNm8G1ioUiHloVp5R4/XsJqx4E6wx+fXm6iO6+C6CiR/tegXmMGH0EW7VFMYEv9kCFpVoOK3kp4tidArCvOWrqvO6qF5jFK/MGFRMR1SXni9Pl/7A04lMPr/nl8Z+OC8XzE2aK4KI/ApoW004UO9DZUiFZOA+jgqIeFWzU+k4axomlvvbm6ctlu64NuqXUGFlWps22ksdnx/l1V5OJ6wZ3hkP6776V6BMdGEFID9IuA2SUYIGirVottS0g7/F8bufCExo099xwhXPXycN+JnMY+lgOExf6NYyBZ8kdeNh+wtF9TiQFttsfyVRXP9HkIom3+AO3YONEjYAjDC0mSRA5iQ4Zkg=
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
status: {}
